global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'clickhouse_exporter'
    static_configs:
      - targets: ['clickhouse_exporter:9116']

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka_exporter:9308']
